Change ActiveRecord::Migration to ActiveRecord::Migration[7.1]
Changed the line ActiveRecord::Migration to ActiveRecord::Migration[7.1]
so that schema loading could work (it is now required for newer versions
of Rails)

Updated and commented out the load schema task since it fails to find
and run the loading of data into the database PostgreSQL container

Added the initialize_profile method and add it to the `after_create`
portion of the User factory because of the NameError I encountered:

NameError: undefined local variable or method `init_profile'
for #<FactoryBot::SyntaxRunner:0x00007eaac2e3c560> (NameError)