Don't force Ubuntu18
Seems to be causing the following error somehow:

```
Installing Bundler
Error: There was an error when attempting to execute the process '/__t/Ruby/2.7.4/x64/bin/gem'. This may indicate the process failed to start. Error: spawn /__t/Ruby/2.7.4/x64/bin/gem ENOENT
```